### ISSUE TITLE
Will Splint can like ACE Tourniquet, we can manually remove it or recovery after ACE Personal  Aid Kit ?

### ISSUE THREAD

**Issue by GodofMonkeys** [Pergor/ADV_Medical#10]
Will Splint can like ACE Tourniquet, we can manually remove it or recovery after ACE Personal  Aid Kit ?
I think this may make Splint more like emergency measures when heal someone, and if situation is green, the medic/doctor can heal people completely and recover the Splint.

**Comment by Pergor** [comment]
Nope. Not possible without a major hassle. Tourniquets are computed in a very odd and special way.

**Comment by GodofMonkeys** [comment]
ok
