### ISSUE TITLE
ACE and Real Life

### ISSUE THREAD

**Issue by antonome** [Pergor/ADV_Medical#14]
Hi there

I have been a paramedic for a number of years, have a degree in Emergency Medicine and Rescue.  Just wanted to give some feedback regarding some of the ACE Medical procedures:

- **For a resus (patient unconscious with no heart rate) I think the procedure should be the following to revive them:**

1. Establish the patient is in a unconscious and no heart rate state
2. As the patient is in this state due to bleeding and hence hypovolaemic shock, wounds should be bandaged first to stop the bleeding
3. An Infusion of some kind need to happen before the patient goes in a state where he can be revived
4. CPR should be performed to prolong the revivable state
5. After the IV and Bandages, the patient is now in a revivale state. It is virtually impossible to revive someone with only CPR and Epinephrine.

A sequence of Shocks via a defibrilator should be delivered to get the heart started at 360J 
For ingame I would suggest:
1. Deliver 1st Shock (25% chance of revival)
2. Give epinephrine
3. Deliver 2nd Shock (50% chance of revival)
4. Give Epinephrine
5. Deliver 3rd Shock (75% chance of revival)
6. Give Amiodorone, as the patient is now in a persistant Ventricular Fibrilation.
7. Deliver 4th Shock (100% chance of revival)

Adenosine does not slow the heart, it actually stops the heart for 10 seconds.  This is usually a treatment for a very specific supraventricular tachycardia and is not useful in a trauma case.  Atropine does not slow the heart, it actually increases the heart rate by blocking the parasympathetic nervous system.  Also never used in a trauma case.

Epinephrine by injection should not be used to increase the BP.  If given via IV, it will probably kill a live patient, and given IntraMuscular (like we do in ARMA) it is almost impossible to know what the effect is.  I would recommend that BP can be increased by IV.  Epinephrine can be used to increase BP, but only if you titrate it through an IV and can manage it per drop rate.  

ACE Medical is a great MOD!  Keep up the good work!

**Comment by Pergor** [comment]
Thank you very much for your comments. I'm not at all affiliated with the ace³ development team. My mod ist just a different take on the ace-medical-system to achieve greater playability with the ace systems at hand.
I'd recommend to carry your suggestions over to the ace-github, as they are currently reworking the whole medical system anyways: https://github.com/acemod/ACE3/releases

**Comment by antonome** [comment]
Ah!  My mistake.  Thanks!
