### ISSUE TITLE
Revive not working

### ISSUE THREAD

**Issue by LeightonThompson** [Pergor/ADV_Medical#15]
Hi there,

We were testing the revive function and we had an issue.
We could get someone back from having no heart rate, and an extremely low blood pressure back to standard using the defibrillator and blood (as you normally would). Once the person was stablised, they wouldn't wake up. We had to use a PAK to wake them.

Thanks 👍 

Here are my settings:
`// ADV - ACE CPR
force force adv_aceCPR_addTime = 20;
force force adv_aceCPR_AED_stationType = """Land_Defibrillator_F""";
force force adv_aceCPR_chance_0 = 3;
force force adv_aceCPR_chance_1 = 10;
force force adv_aceCPR_chance_2 = 20;
force force adv_aceCPR_chance_aed = 85;
force force adv_aceCPR_enable = true;
force force adv_aceCPR_maxTime = 1200;
force force adv_aceCPR_useLocation_AED = 0;`

`// ACE Medical
force force ace_medical_ai_enabledFor = 2;
force force ace_medical_AIDamageThreshold = 1;
force force ace_medical_allowLitterCreation = true;
force force ace_medical_allowUnconsciousAnimationOnTreatment = false;
force force ace_medical_amountOfReviveLives = -1;
force force ace_medical_bleedingCoefficient = 1;
force force ace_medical_blood_enabledFor = 2;
force force ace_medical_consumeItem_PAK = 1;
force force ace_medical_consumeItem_SurgicalKit = 0;
force force ace_medical_delayUnconCaptive = 3;
force force ace_medical_enableAdvancedWounds = true;
force force ace_medical_enableFor = 0;
force force ace_medical_enableOverdosing = true;
force force ace_medical_enableRevive = 1;
force force ace_medical_enableScreams = true;
force force ace_medical_enableUnconsciousnessAI = 1;
force force ace_medical_enableVehicleCrashes = true;
force force ace_medical_healHitPointAfterAdvBandage = false;
force force ace_medical_increaseTrainingInLocations = false;
force force ace_medical_keepLocalSettingsSynced = true;
force force ace_medical_level = 2;
force force ace_medical_litterCleanUpDelay = 0;
force force ace_medical_litterSimulationDetail = 2;
force force ace_medical_maxReviveTime = 480;
force force ace_medical_medicSetting = 2;
force force ace_medical_medicSetting_basicEpi = 1;
force force ace_medical_medicSetting_PAK = 2;
force force ace_medical_medicSetting_SurgicalKit = 2;
force force ace_medical_menu_allow = 1;
force force ace_medical_menu_maxRange = 3;
force force ace_medical_menu_openAfterTreatment = true;
force force ace_medical_menu_useMenu = 1;
force force ace_medical_menuTypeStyle = 0;
force force ace_medical_moveUnitsFromGroupOnUnconscious = false;
force force ace_medical_painCoefficient = 1;
ace_medical_painEffectType = 1;
force force ace_medical_painIsOnlySuppressed = true;
force force ace_medical_playerDamageThreshold = 1;
force force ace_medical_preventInstaDeath = true;
force force ace_medical_remoteControlledAI = true;
force force ace_medical_useCondition_PAK = 1;
force force ace_medical_useCondition_SurgicalKit = 1;
force force ace_medical_useLocation_basicEpi = 0;
force force ace_medical_useLocation_PAK = 2;
force force ace_medical_useLocation_SurgicalKit = 0;`

**Comment by Pergor** [comment]
Have you administered morphine to reduce the pain level?

**Comment by LeightonThompson** [comment]
It seems zeus injuring someone makes them be in a lot more pain. When we tested naturally, it worked with just one morphine. Thanks.
