### ISSUE TITLE
Limb checkup feature

### ISSUE THREAD

**Issue by ArwynFr** [Pergor/ADV_Medical#16]
IRL, standard procedures regarding first aid checkup with traumatic concept involved, include a limb analysis for all 4 members on both sensibility and mobility. This allows first aid teams to hasty identify potential limb injuries that have mobility consequences. It would be nice to provide a simple (but perhaps lengthy) limb analysis that would display whether each limb has a traumatic wound (when damage is above threshold) or not. This feature shall be added to in the heart frequency / blood pressure / consciousness test menu.

This would allow first aid respondents to tell whether victims needs a splint or not. For lower members its easy to detect, as victims will then limb. Regarding arms, the diagnostic relies on the victim's ability to differentiate aiming precision which is usually somewhat limited to experienced ACE players.

**Comment by Pergor** [comment]
https://github.com/Pergor/ADV_Medical/commit/47d1c83ead8cdda0732e6488b55c8fdb424ab504
Will be published with the next update.
