### ISSUE TITLE
AED Station can't handle the item

### ISSUE THREAD

**Issue by Katalam** [Pergor/ADV_Medical#18]
*Description*
If you leave the AED Item on the ground, it will bring up a AED Station. But if you take it again and the weapon ground holder is not empty, you can still use the station at the weapon holder.

**Comment by Pergor** [comment]
Upsy-Daisy...

**Comment by Pergor** [comment]
Tada: https://github.com/Pergor/ADV_Medical/commit/e27a2462e4a07cd39b1ba5acae01403ab5c788bd
