### ISSUE TITLE
Feature Request: Ability to turn off mod functionality in CBA Settings

### ISSUE THREAD

**Issue by DeliciousJaffa** [Pergor/ADV_Medical#2]
The ability to turn off the functionality of advCPR and advSplint would be useful for units like mine where we require different settings/functionality for each server but try and keep the mods uniform to avoid player confusion.

For example, it is possible to completely disable Ace's medical system without removing the PBO

**Comment by Pergor** [comment]
Seems like a good idea. I could simply reroute the function of the CPR to the regular ACE function and disable the splint-action. I'll take a look into it.

**Comment by Pergor** [comment]
That should do it: https://github.com/Pergor/ADV_Medical/commit/e99ec730a804075824d210b6889c4d5cf8b65fbb
