### ISSUE TITLE
Arma 3 v1.90 Fatal Error: Player cannot connect to server with this mod.

### ISSUE THREAD

**Issue by GoldJohnKing** [Pergor/ADV_Medical#22]
After Arma 3 updated to v1.90, player cannot connect to server which enabled signature check with this mod. And in the server browser of the game, this mod is red in "Mod Info" column.

It might be caused by signature not competitable to the newest version, please check it soon.

**Comment by Pergor** [comment]
It's a known problem with a couple of causes and solutions: https://forums.bohemia.net/forums/topic/222192-190-update-troubleshooting/
Right now I don't have any reasons to believe it's a problem with the signatures of my modfiles. Will keep an eye on that though.

**Comment by GoldJohnKing** [comment]
I've read that thread and I've tried those suggested methods, but things goes on well for other mods, just except ADV.

- I'm using @adv_aceSplint from Steam Workshop.
- As I described above, I've deleted cache.ch files both on server and clients with steam and Arma 3 closed. Players got "connection lost" error only if I have @adv_aceSplint on both server and clients, but no signature error hints appear in server dialog. However, if server has it but clients dont have it, or server and clients both dont have it, players can connect to server normally.

**Comment by Pergor** [comment]
Alright... Let's go a little further:
- Are you playing on a dedicated windows server or a dedicated linux server?
- Does the problem occur with every client connecting to the server or only with some?

**Comment by GoldJohnKing** [comment]
- OS: Windows Server 2019
- All clients have lost connection error if they connect to the server if we have @adv_aceSplint in or mod preset. I'm just thinking if it has some compability issues with other mods? I'll test it soon.

**Comment by Pergor** [comment]
I suppose you tested only with the bare necessities: cba, ace, adv_aceSplint together and cba and ace only. Otherwise it's not really safe to assume that @adv_aceSplint is a possible cause.

**Comment by GoldJohnKing** [comment]
I've tried to redownload the mod, the the problem solved.

Please notice that re-upload the mod to server (for example, copy from client to server through mstsc) has no use, have to undiscribe then discribe (no matter on clientside then upload or via SteamCMD on server).

So, I think it's not the mod's problem.
