### ISSUE TITLE
[Steam 1.5.6] CPR doesn't seem to do anything.

### ISSUE THREAD

**Issue by HalfdeadKiller** [Pergor/ADV_Medical#27]
From what I understood CPR with this mod is supposed to function like epinephrine regarding the revive state. I've done testing where I've turned on basic medical with revive on, and then shot an AI until he was not functional. I then bandaged, gave blood, and removed pain from the AI unit, and set the CPR chance to 100 prior to testing. Upon giving CPR, the AI Unit simply stood laying on the ground.

How is this mod supposed to work exactly regarding CPR?

**Comment by Pergor** [comment]
ADV - ACE CPR is not running when ace basic medical is active. It's only for ace advanced medical.
